baseURL = "https://blackcaesar0.com/"
title = "Cyber security blog"
#themesDir = "../.."
theme = "hugo-theme-m10c"
pluralizeListTitles = false
author = "blackcaesar0"
disableHugoGeneratorInject = true
[pagination]
  pagerSize = 8

[menu]
  [[menu.main]]
    identifier = "hackthebox"
    name = "Hackthebox"
    url = "/hackthebox/"
    weight = 4
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "blackcaesar0"
  description = "Exploring cybersecurity, ethical hacking, and digital forensicsâ€”one exploit at a time."
  menu_item_separator = " - "
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/blackcaesar0"
  [[params.social]]
    icon = "brand-linkedin"
    name = "linkedin"
    url = "https://www.linkedin.com/in/blackcaesar0"
#  [[params.social]]
#    icon = "brand-x"
#    name = "X"
#    url = "https://twitter.com/gohugoio"
#  [[params.social]]
#    icon = "brand-mastodon"
#    name = "Twitter"
#    url = "https://twitter.com/gohugoio"

  # Default theme
#   [params.style]
#     darkestColor = "#242930"
#     darkColor = "#353b43"
#     lightColor = "#afbac4"
#     lightestColor = "#ffffff"
#     primaryColor = "#57cc8a"

  # Green theme
  # [params.style]
  #   darkestColor = "#315659"
  #   darkColor = "#253031"
  #   lightColor = "#96a879"
  #   lightestColor = "#fff"
  #   primaryColor = "#dad865"

  # Red theme
  # [params.style]
  #   darkestColor = "#d35050"
  #   darkColor = "#212121"
  #   lightColor = "#d6d6d6"
  #   lightestColor = "#d3d3d3"
  #   primaryColor = "#ffffff
[params.style]
  darkestColor  = "#000000"   # Background
  darkColor     = "#111111"   # Slightly lighter sections
  lightColor    = "#eeeeee"   # Regular text (light gray or near white)
  lightestColor = "#ffffff"   # Hover/active text
  primaryColor  = "#0af0ff"   # Accent (links, headings, etc)
 

